# Use an official Python runtime as the base image
FROM python:3.8

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file to the container
COPY requirements.txt .

# Install the dependencies
RUN pip install -r requirements.txt

COPY . .

RUN apt-get -y update
EXPOSE 8080
CMD ["python", "/app/src/upload_server.py"]
