# Use an official Python runtime as the base image
FROM python:3.8

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file to the container
COPY requirements.txt .

# Install the dependencies
RUN pip install -r requirements.txt

COPY . .

RUN apt-get -y update

RUN apt-get install -y ffmpeg

CMD ["python", "/app/create_videos.py", "--use-cached-communities", "--save-in-firebase", "--include-member-videos"]
