# Use an official Python runtime as the base image
FROM ubuntu

RUN apt-get update
RUN apt-get install -y python3 python3-pip ffmpeg cron

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file to the container
COPY requirements.txt .

# Install the dependencies
RUN pip install -r requirements.txt

COPY . .

COPY crontab /etc/cron.d/

RUN touch /var/log/cron.log

CMD cron && tail -f /var/log/cron.log